### ISSUE TITLE
error when computing cross-correlations with demean

### ISSUE THREAD

**Issue by imme-w** [PeterMakus/SeisMIC#82]
Hi Peter, I get an error if I try to run my correlations with demean in the TDPreprocessing:
```
  corr_args: {'TDpreProcessing': [{'function': 'seismic.correlate.preprocessing_td.demean','args': {}}], 
```
This is the error:
```
2024-11-26 10:51:07,059 - WARNING - No existing data found.
Automatically setting preprocess_subdiv to False to optimise performance.

  0%|          | 0/1 [00:00<?, ?it/s]
  0%|          | 0/1 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/home/wienki/seismic_7-11/correlate.py", line 26, in <module>
    st = c.pxcorr()
         ^^^^^^^^^^
  File "/home/wienki/.conda/envs/seismicenv-python3.11/lib/python3.11/site-packages/seismic/correlate/correlate.py", line 354, in pxcorr
    cst.extend(self._pxcorr_inner(st, inv))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wienki/.conda/envs/seismicenv-python3.11/lib/python3.11/site-packages/seismic/correlate/correlate.py", line 390, in _pxcorr_inner
    A, startlags = self._pxcorr_matrix(A)
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wienki/.conda/envs/seismicenv-python3.11/lib/python3.11/site-packages/seismic/correlate/correlate.py", line 671, in _pxcorr_matrix
    A[ind, :] = func(A[ind, :], proc['args'], params)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: demean() takes 1 positional argument but 3 were given
```
I looked at the demean function and it indeed only takes one argument:
```
def demean(data: np.ndarray) -> np.ndarray:
    """
    Demean data

    :param data: 1 or 2D array
    :type data: np.ndarray
    :return: demeaned data
    :rtype: np.ndarray
    """
    return data - np.nanmean(data, axis=-1, keepdims=True)
```
How can I solve this error?
I am using the `dev` version by the way!
Thanks a lot!

**Comment by PeterMakus** [comment]
Hi Imme,
You are right this is a bit unfortunate because demean was initially meant as an internal function but this is not documented. The way it was meant, was to use ``detrend``with ``type=constant``, which would then call ``demean``. However, I have now pushed a change to the *dev* branch that allows to allow the direct use of demean. So you could also just pull the latest changes :)


Peter

P.s. Going to close this now
